acordion/urls.py
from django.urls import path

from . import views
app_name = 'acordion'

urlpatterns = [
    path("acordion", views.mini_profile_view, name="mini_profile")
]

book/urls.py
from django.urls import path

from . import views
app_name = 'book'

urlpatterns = [
    path("book", views.index, name="book"),
    path("data/", views.fungsi_data)
]

home/urls.py
from django.urls import path

from . import views
app_name = 'home'

urlpatterns = [
    path('', views.page1, name='home'),
    path('gallery', views.page2, name='gallery'),
    path('story1', views.page3, name='story1'),
    path('FormProduct',views.product_create_view, name= 'product_create'),
    path('ListProduct', views.list, name='product_list'),
    path('delete/<str:id>', views.delete, name="product_delete"),
    path('<int:id>',views.detail),
    path('update/<str:id>', views.update, name='update')
]

kegiatan/urls.py
from django.urls import path

from . import views
app_name = 'kegiatan'

urlpatterns = [
    path('card_kegiatan', views.index, name='card_kegiatan'),
    path('tambah', views.tambah, name='tambah'),
    path('tambah_peserta/', views.tambah_peserta, name='tambah_peserta'),


]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    path('register', views.register, name='register'),
    path('login/', views.logging_in, name='logging_in'),
    path('logout/', views.logging_out, name='logging_out')
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('kegiatan.urls')),
    path('', include('acordion.urls')),
    path('', include('book.urls')),
    path('', include('login.urls')),
]

home/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    namaMatkul = models.CharField(max_length = 120)
    dosen      = models.CharField(max_length = 120)
    jumlahSks  = models.IntegerField()
    semester   = models.CharField(max_length = 120)
    ruangKelas = models.CharField(max_length = 120)

    def __str__(self):
        return self.namaMatkul

home/forms.py
from django import forms

from .models import Product

class ProductForm(forms.ModelForm):
    namaMatkul = forms.CharField(label='Nama Matkul :')
    dosen      = forms.CharField(label='Dosen   :')
    jumlahSks  = forms.IntegerField(label='Jumlah SKS :')
    semester   = forms.CharField(label='Semester  :')
    ruangKelas = forms.CharField(label='Ruang Kelas :')
    
    class Meta:
        model = Product
        fields = '__all__'

home/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from .forms import ProductForm
from .models import Product

# Create your views here.

def page1(request):
    return render(request, 'home/myblog.html')

def page2(request):
    return render(request, 'home/gallery.html')

def page3(request):
    return render(request, 'home/story1.html')

def list(request):
    listp = Product.objects.all()
    return render(request, 'home/product_list.html' , {'listp':listp})

def product_create_view(request):
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/ListProduct')
    return render(request, 'home/product_create.html', {'form':form})

def delete(request,id):
    item = Product.objects.get(id=id)
    if request.method == 'POST':
        item.delete()
        return redirect('/ListProduct')
    return render(request, 'home/product_delete.html', {'item':item})

def detail(request,id):
    prod = Product.objects.get(id=id)
    return render (request, 'home/product_detail.html',{'prod':prod})

def update(request, id):
    prod = Product.objects.get(id=id)
    form = ProductForm(instance=prod)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=prod)
        if form.is_valid():
            form.save()
            return redirect('/ListProduct')

    return render(request, 'home/product_create.html', {'form':form})

home/templates/home/footer.html
{% load static %}
<footer>
    <div class="footer">
        <div class="row">
            <div class="col-sm-6">
              <h3>Quotes</h3>
              <p>We have to step back little bit to jump further in our lives</p>
            </div>
            <div class="col-sm-6">
            <h3>Hit Me Up</h3>
            <a class="fa fa-linkedin" href="https://www.linkedin.com/in/nadila-tusifa-297362194/" ></a>
            <a class="fa fa-instagram" href="https://www.instagram.com/nadiladrew/"></a>
            <a class="fa fa-google" href="mailto:nadilatusifa83@gmail.com"></a>
            </div>
        </div>
    </div>
</footer>
</html>

home/templates/home/gallery.html
{% load static %}

<body>
  <title>Nadila Tusifa</title>
  <div class="header">
    <h1>Gallery</h1>
</div>

{% include 'home/header.html' %}
      <div class="gallery">
        <div class="row">
          <div class="col-sm-4">
            <p>My first organization on collage is DPM.<br></p>
              <img src="{% static 'home/images/dpm.jpg' %}" width="300" height="450" class="img-fluid" alt="Responsive image" >
          </div>

          <div class="col-sm-4">
            <p>This is my first theater show at UIAW 2019 <br></p>
            <img src="{% static 'home/images/pict2.jpg' %}"  width="300" height="300" class="img-fluid" alt="Responsive image">
          </div>

          <div class="col-sm-4">
            <p>My last outside OOTD photo in pandemic year :) </p>
            <img src="{% static 'home/images/pict1.jpg' %}" width="300" height="300" class="img-fluid" alt="Responsive image">
          </div>

          <div class="col-sm-4">
            <p>See you at the future</p>
            <img src="{% static 'home/images/light.jpg' %}" width="300" height="300" class="img-fluid" alt="Responsive image">
          </div>

        <div class="col-sm-4">
          <p>At yayoi kusama exhibition</p>
          <img src="{% static 'home/images/mcn.jpg' %}" width="300" height="300" class="img-fluid" alt="Responsive image">
        </div>

        <div class="col-sm-4">
          <p>No matter how far i'll go, i will back to you</p>
          <img src="{% static 'home/images/infi2.jpg' %}" width="300" height="300" class="img-fluid" alt="Responsive image">
        </div>
    
        <div class="col-sm-4">
          <p>Towards infinity and beyond</p>
          <img src="{% static 'home/images/infi.jpg' %}" width="300" height="300" class="img-fluid" alt="Responsive image">
        </div>

        <div class="col-sm-4">
          <p>Is it looks scary enough? :)</p>
          <img src="{% static 'home/images/alive.jpg' %}" width="300" height="500" class="img-fluid" alt="Responsive image">
        </div>

        <div class="col-sm-4">
          <p>At Haluuu art exhibition</p>
          <img src="{% static 'home/images/halu.jpg' %}" width="300" height="300" class="img-fluid" alt="Responsive image">
        </div>
    
      </div>
    </div>


</body>
{% include 'home/footer.html' %}

home/templates/home/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'home/desain.css' %}">
    
</head>

<body>

    <nav class="navbar navbar-expand-sm justify-content-center">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:gallery' %}">Gallery</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'home:story1' %}">Story1</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'home:product_list' %}">Courses</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'kegiatan:card_kegiatan' %}">Activities</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'acordion:mini_profile' %}">Acoridon</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'book:book' %}">Library</a>
          </li>
          {% if not request.user.is_authenticated %}
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'login:logging_in' %}">Login</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'login:register' %}">Register</a>
          </li>
          {% else %}
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'login:logging_out' %}">Logout</a>
          </li>
          {% endif %}
        </ul>
    </nav>

  

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'acordion/js/script.js' %}"></script>

</body>

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>Hello</title>
</head>
<body>
    <h1>Hello World</h1>
</body>
</html>

home/templates/home/myblog.html
{% load static %}
<title>Nadila Tusifa</title>

<body>
  <div class="header">
    <h1>Welcome to My Profile</h1>
  </div>
  
  {% include 'home/header.html' %}

<div class="container">
    <div class="row">
        <div calss="col-sm-6">
            <img src="{% static 'home/images/nadila.jpg' %}" width="200" heigh="300" alt="Fotoku">
            <br>
            <br>
            <h2> Nadila Tusifa <br> </h2>
            <p>Hi, my name is nadila. I was born in Jakarta, 12 August 2000<br>
            I currently study in University of Indonesia as a computer science student and I have many interest such as photography, theater, dance, and also technology<br>
            <img src="{% static 'home/images/kamera.png' %}" width="150" heigh="150" class="img-fluid" alt="Responsive image">
            <img src="{% static 'home/images/teater.png' %}" width="150" heigh="150" class="img-fluid" alt="Responsive image">
            <img src="{% static 'home/images/tari.png' %}" width="200" heigh="200" class="img-fluid" alt="Responsive image">
            <img src="{% static 'home/images/laptop.png' %}" width="100" heigh="100" class="img-fluid" alt="Responsive image">
            </p> 
        </div>
    </div>
</div>

<div class="ed">
  <h4>Education</h4>
  <hr size=12px width=100% style = "border: 5px solid orange; border-radius: 10px;">
  <br>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <p>SMPN 5 Jakarta<br></p>
        <img src="{% static 'home/images/smp5.png' %}" width="200" heigh="200" alt="SMPN5 JKT" class="img-fluid">
    </div>
    <div class="col-sm-4">
      <p>SMAN 1 Jakarta<br></p>
      <img src="{% static 'home/images/sman1.png' %}" width="200" heigh="200" alt="SMAN1 JKT" class="img-fluid">
    </div>
    <div class="col-sm-4">
      <p>Universitas Indonesia</p>
      <img src="{% static 'home/images/UI.png' %}" width="200" heigh="200" alt="UI" class="img-fluid">
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>

<div class="ed">
  <h4>Experiences</h4>
  <hr size=12px width=100% style = "border: 5px solid orange; border-radius: 10px;">
  <br>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <p>Vice President Human Resource<br></p>
        <img src="{% static 'home/images/logodpm.png' %}" width="200" heigh="200" class="img-fluid" alt="Responsive image">
    </div>
    <div class="col-sm-4">
      <p>Staff of Media Partner<br><br></p>
      <img src="{% static 'home/images/logocf.jpg' %}" width="200" heigh="200" class="img-fluid" alt="Responsive image">
    </div>
    <div class="col-sm-4">
      <p>Staff of Sponsorship<br><br></p>
      <img src="{% static 'home/images/logoperak.png' %}" width="200" heigh="200" class="img-fluid" alt="Responsive image">
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>


{% include 'home/footer.html' %}
  
</body>
</html>

home/templates/home/product_create.html
{% load crispy_forms_tags %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="header">
  <h1>Courses</h1>
</div>
{% include 'home/header.html' %}
<br>
<div class="container">
    <!-- <div class="row justify-content-center">
      <div class="col-8"> -->
        <h2>Add Course</h2>
        <hr class="mt-0 mb-4">
        <form method="POST">
          {% csrf_token %}
          {{ form|crispy }}
          <br>
          <br>
          <button type="submit" class="btn btn-primary">Submit</button>
          <a type="button" class="btn btn-light" href="{% url 'home:product_list' %}"><b>Back</b></a>
        </form>
      
        <br>
      </div>
    </div>
  </div>
<br>

{% endblock %}
{% include 'home/footer.html' %}

home/templates/home/product_delete.html
{% load static %}
{% block content %}

<div class="header">
  <h1>Courses</h1>
</div>

{% include 'home/header.html' %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Delete course</b></h2>
        <hr class="mt-0 mb-4">
        
        <form action="{% url 'home:product_delete' item.id %}" method='POST'>
            {% csrf_token %}
            <h5 class="featurette-heading">Do you want to delete the course "{{item}}"?</h5>
            <br>
            <button type="submit" class="btn btn-danger"><b>Yes</b></button>
            <a type="button" class="btn btn-info" href="{% url 'home:product_list' %}"><b>Cancel</b></a>

      </div>
    </div>
  </div>
<br>

{% endblock %}
{% include 'home/footer.html' %}

home/templates/home/product_detail.html
{% load static %}
{% block content %}
<div class="header">
  <h1>Courses</h1>
</div>
{% include 'home/header.html' %}
<br>
<div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>Course Detail</b></h2>
        <table class="table" style="text-align: left;" >
        <tbody >
          <tr>
            <th scope="row">Nama matkul</th>
            <td>{{ prod.namaMatkul }}</td>
          </tr>
          <tr>
            <th scope="row">Dosen</th>
            <td>{{ prod.dosen }}</td> 
          </tr>
          <tr>
            <th scope="row">Sks</th>
            <td>{{ prod.jumlahSks }}</td>
          </tr>
          <tr>
            <th scope="row">Semester</th>
            <td>{{ prod.semester }}</td>
          </tr>
          <tr>
            <th scope="row">Ruang Kelas</th>
            <td>{{ prod.ruangKelas }}</td>
          </tr>
        </tbody>
      </table>
      <a class="btn btn-danger" href="{% url 'home:product_delete' prod.id %}">Delete Course</a>
      <a type="button" class="btn btn-light" href="{% url 'home:product_list' %}"><b>Back</b></a>
      <a type="button" class="btn btn-info" href="{% url 'home:update' prod.id %}">Update Course</a>
  </div>
</div>
</div>
</br>
{% endblock %}
{% include 'home/footer.html' %}

home/templates/home/product_list.html
{% load static %}

{% block content %}
<div class="header">
  <h1>Courses</h1>
</div>
{% include 'home/header.html' %}
<br>
    <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <h2 class="featurette-heading"><b>My Current Courses</b></h2>
        <hr class="mt-0 mb-4">
        <div class="list-group">
            {% for i in listp %}
            <a href="{{ i.id }}" class="list-group-item list-group-item-action"><b>{{ i.namaMatkul }}</b></a>
            {% endfor %}
        </div>
        <br>
        <a class="btn btn-dark" href="{% url 'home:product_create' %}"><b>Add course</b></a>
      <br>
    </div>
  </div>
</div>
<br>


{% endblock %}
{% include 'home/footer.html' %} 

home/templates/home/story1.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'home/desain.css' %}">
        <title>Nadila tusifa</title>
    </head>

<body>
    <div class="header">
        <h1>Story1</h1>
    </div>
{% include 'home/header.html' %}

<p style="color:black ; text-align: center; font-size: 20px;">Nama: Nadilatusifa <br>
    Angkatan: Maung <br>
    Hobi: Menari,membaca novel, tidur <br>
    Deskripsi tentang saya: Ilkom 2019, anak teater sejak smp, sangat suka acting, suka kucing<br>
    Tempat kuliah: Universitas Indonesia <br>
    Riwayat pendidikan : <br>
    SMPN 5 jakarta <br>
    SMAN 1 jakarta <br>
    Universitas Indonesia <br>
    Sosial media : nadiladrew <br>
    Foto : <br>
    <img src="{% static 'home/images/pict1.jpg' %}" width="200" heigh="300" alt="Kucing"> <br>
</p>

{% include 'home/footer.html' %}
</body>
</html>