book/urls.py
from django.urls import path

from . import views
app_name = 'book'

urlpatterns = [
    path("book", views.index, name="book"),
    path("data/", views.fungsi_data)
]

home/urls.py
from django.urls import path

from . import views
app_name = 'home'

urlpatterns = [
    path('', views.page1, name='home'),
    path('gallery', views.page2, name='gallery'),
    path('story1', views.page3, name='story1'),
    path('FormProduct',views.product_create_view, name= 'product_create'),
    path('ListProduct', views.list, name='product_list'),
    path('delete/<str:id>', views.delete, name="product_delete"),
    path('<int:id>',views.detail),
    path('update/<str:id>', views.update, name='update')
]

kegiatan/urls.py
from django.urls import path

from . import views
app_name = 'kegiatan'

urlpatterns = [
    path('card_kegiatan', views.index, name='card_kegiatan'),
    path('tambah', views.tambah, name='tambah'),
    path('tambah_peserta/', views.tambah_peserta, name='tambah_peserta'),


]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('kegiatan.urls')),
    path('', include('acordion.urls')),
    path('', include('book.urls')),
    path('', include('login.urls')),
]

kegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length = 500)

    def __str__(self):
        return self.namaKegiatan

class Participant(models.Model):
    nama = models.CharField(max_length = 200)
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.kegiatan) +"dan" + self.nama

kegiatan/forms.py
from django import forms
from .models import Kegiatan,Participant

class KegiatanForm(forms.ModelForm):
    namaKegiatan = forms.CharField(label='Nama Kegiatan : ')

    class Meta:
        model = Kegiatan
        fields = '__all__'
    
class ParticipantForm(forms.ModelForm):
    class Meta:
        model = Participant
        fields = '__all__'

kegiatan/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404

from .forms import KegiatanForm, ParticipantForm
from .models import Kegiatan, Participant
# Create your views here.

def index(request):
    keg = Kegiatan.objects.all()
    peserta = Participant.objects.all()
    keg_par = []
    for kegiatan in keg:
        kegiatan_partic = []

        for participant in peserta:
            if (str(participant.kegiatan) == str(kegiatan)):
                kegiatan_partic.append(participant)
        keg_par.append((kegiatan,kegiatan_partic))
        
    context= {
        'keg':keg,
        'keg_par' : keg_par,
        
    }
    return render(request, 'kegiatan/card_kegiatan.html', context)

def tambah(request):
    form = KegiatanForm()
    if request.method == 'POST':
        form = KegiatanForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/card_kegiatan')
    return render(request, 'kegiatan/kegiatan.html', {'form':form})


def tambah_peserta(request):
    form = ParticipantForm()
    if request.method == 'POST':
       form = ParticipantForm(request.POST)
       if form.is_valid():
           form.save()
           return redirect('/card_kegiatan')
    return render(request, 'kegiatan/form_peserta.html',{'form':form})


    
    

kegiatan/templates/kegiatan/card_kegiatan.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<header>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'kegiatan/desain.css' %}">
</header>
    <div class="header">
        <h1>Activities</h1>
    </div>
    {% include 'home/header.html' %}
    <div class="container">
        <!-- <div class="row justify-content-center">
          <div class="col-8"> -->


            <div class="container-fluid justify-content-center">
                <div class="row justify-content-center"></div>
                <h2 class="featurette-heading"><b>My Current Activities</b></h2>
               {% for a in keg_par %}
              

              
                <div class="row justify-content-center">
                    <div class="col-sm-3">
                        <div class="card border-primary mb-3" style="max-width: 18rem;">
                        <div class="card-header">{{ a.0.namaKegiatan }}</div>
                        <div class="card-body text-primary">
                            <p class="card-text">
                                <a type="button" class="btn btn-info" href="{% url 'kegiatan:tambah_peserta' %}">Join activity</a>
                                <p>{% for b in a.1 %}</p><br>
                                {{ b.nama }}
                                {% endfor %}

                            </p>
                        </div>
                        </div>
                    </div>
                </div>
            </div>

                <br>
                
            {% endfor %}
            <br> 
            <a class="btn btn-dark justify-content-center " href="{% url 'kegiatan:tambah' %}"><b>Add activitiy</b></a>
            <br>
            <br> 
    </div>      


         
</html>

{% endblock %}
{% include 'home/footer.html' %}

kegiatan/templates/kegiatan/footer.html
{% load static %}
<footer>
    <div class="footer">
        <div class="row">
            <div class="col-sm-6">
              <h3>Quotes</h3>
              <p>We have to step back little bit to jump further in our lives</p>
            </div>
            <div class="col-sm-6">
            <h3>Hit Me Up</h3>
            <a class="fa fa-linkedin" href="https://www.linkedin.com/in/nadila-tusifa-297362194/" ></a>
            <a class="fa fa-instagram" href="https://www.instagram.com/nadiladrew/"></a>
            <a class="fa fa-google" href="mailto:nadilatusifa83@gmail.com"></a>
            </div>
        </div>
    </div>
</footer>
</html>

kegiatan/templates/kegiatan/form_peserta.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="header">
        <h1>Activities</h1>
    </div>
{% include 'home/header.html' %}
<br>
<div class="container">
    <!-- <div class="row justify-content-center">
      <div class="col-8"> -->
        <h2>Join Activity</h2>
        <hr class="mt-0 mb-4">
        <form method="POST">
          {% csrf_token %} 
          {{ form|crispy }}
          <br>
          <br>
          <button type="submit" class="btn btn-primary">Submit</button>
          <a type="button" class="btn btn-light" href="{% url 'kegiatan:card_kegiatan' %}"><b>Back</b></a>
        </form>
</div>
{% endblock %}
{% include 'home/footer.html' %}

kegiatan/templates/kegiatan/header.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'home/desain.css' %}">
    
</head>

<header>
   
    <nav class="navbar navbar-expand-sm justify-content-center">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home:gallery' %}">Gallery</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'home:story1' %}">Story1</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'home:product_list' %}">Courses</a>
          </li>
          <li class ="nav-item">
            <a class="nav-link" href="{% url 'kegiatan:card_kegiatan' %}">Activities</a>
          </li>
        </ul>
      </nav>
</header>

kegiatan/templates/kegiatan/kegiatan.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="header">
        <h1>Activities</h1>
    </div>
{% include 'home/header.html' %}

    <br>
<div class="container">
    <!-- <div class="row justify-content-center">
      <div class="col-8"> -->
        <h2>Add Activity</h2>
        <hr class="mt-0 mb-4">
        <form method="POST">
          {% csrf_token %} 
          {{ form|crispy }}
          <br>
          <br>
          <button type="submit" class="btn btn-primary">Submit</button>
          <a type="button" class="btn btn-light" href="{% url 'kegiatan:card_kegiatan' %}"><b>Back</b></a>
        </form>

</div>
{% endblock %}
{% include 'home/footer.html' %}